name: Setup Rust Environment

inputs:
  key:
    description: Cache key
    required: true
  toolchain:
    description: Pass-through to toolchain on actions-rs
    default: stable
    required: false
  components:
    description: Pass-through to components on actions-rs
    required: false

runs:
  using: composite
  steps:
    - name: Remove rustfmt
      run: rm -f ~/.cargo/bin/rustfmt ~/.cargo/bin/cargo-fmt
      shell: bash

    - name: Install Rustup
      shell: bash
      run: which rustup || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash || true

    - name: Update Rustup
      shell: bash
      run: rustup self update || true

    - name: Update
      shell: bash
      run: rustup update || true

    - name: Install Toolchain
      uses: dtolnay/rust-toolchain@stable
      id: toolchain-install
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Set default
      shell: bash
      run: rustup default ${{ inputs.toolchain }}
