[package]
name = "zipsign"
description = "Sign a file with an ed25519 signing key"
version = "0.1.0"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
license = "MIT OR Apache-2.0 WITH LLVM-exception"

[dependencies]
base64 = "0.21.4"
clap = { version = "4.4.2", features = ["derive"] }
ed25519-dalek = { version = "2.0.0", features = ["digest", "rand_core", "zeroize"] }
pretty-error-debug = "0.3.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
thiserror = "1.0.48"
zip = { version = "0.6.6", default-features = false }
