# Keep in the same order as <https://doc.rust-lang.org/cargo/reference/manifest.html>
table_order = [
    "package",
    # targets
    "lib",
    "bin",
    "example",
    "test",
    "bench",
    # dependencies
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "target",
    # misc
    "badges",
    "features",
    "lints",
    "patch",
    "replace",
    "profile",
    "workspace",
]
